<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<testsuite failures="1" name="cucumber.runtime.formatter.JUnitFormatter" skipped="0" tests="1" time="0.290491">
<testcase classname="Title of your feature" name="SELECT KTP Number Customer From Table SLIK_DATA_CUSTOMER" time="0.290491">
<failure message="java.sql.SQLException: ORA-00604: error occurred at recursive SQL level 1&#10;ORA-20100: You are not allowed to connect to the database in this time.&#10;ORA-06512: at line 91&#10;&#10;&#9;at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:450)&#10;&#9;at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:392)&#10;&#9;at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:385)&#10;&#9;at oracle.jdbc.driver.T4CTTIfun.processError(T4CTTIfun.java:1018)&#10;&#9;at oracle.jdbc.driver.T4CTTIoauthenticate.processError(T4CTTIoauthenticate.java:501)&#10;&#9;at oracle.jdbc.driver.T4CTTIfun.receive(T4CTTIfun.java:522)&#10;&#9;at oracle.jdbc.driver.T4CTTIfun.doRPC(T4CTTIfun.java:257)&#10;&#9;at oracle.jdbc.driver.T4CTTIoauthenticate.doOAUTH(T4CTTIoauthenticate.java:437)&#10;&#9;at oracle.jdbc.driver.T4CTTIoauthenticate.doOAUTH(T4CTTIoauthenticate.java:954)&#10;&#9;at oracle.jdbc.driver.T4CConnection.logon(T4CConnection.java:639)&#10;&#9;at oracle.jdbc.driver.PhysicalConnection.connect(PhysicalConnection.java:666)&#10;&#9;at oracle.jdbc.driver.T4CDriverExtension.getConnection(T4CDriverExtension.java:32)&#10;&#9;at oracle.jdbc.driver.OracleDriver.connect(OracleDriver.java:566)&#10;&#9;at java_sql_DriverManager$getConnection.call(Unknown Source)&#10;&#9;at Conn_DB.connectDB(Conn_DB.groovy:63)&#10;&#9;at Conn_DB$connectDB.call(Unknown Source)&#10;&#9;at CustomKeywords.Conn_DB.connectDB(CustomKeywords.groovy:180)&#10;&#9;at try_it_out_Conn_DB.Conn_DB(try_it_out_Conn_DB.groovy:61)&#10;&#9;at ✽.Connect to Database(/Users/chaidir.pratama01/Katalon Studio/IST_Automation_Git/Include/features/IST_Real/SLIK/SLIK Gateway Customer/SELECT_KTP_NUMBER_CUSTOMER_from_DB.feature:25)&#10;"><![CDATA[Given Connect to Database...................................................failed
And Check KTP Number Customer in DB.........................................skipped

StackTrace:
java.sql.SQLException: ORA-00604: error occurred at recursive SQL level 1
ORA-20100: You are not allowed to connect to the database in this time.
ORA-06512: at line 91

	at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:450)
	at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:392)
	at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:385)
	at oracle.jdbc.driver.T4CTTIfun.processError(T4CTTIfun.java:1018)
	at oracle.jdbc.driver.T4CTTIoauthenticate.processError(T4CTTIoauthenticate.java:501)
	at oracle.jdbc.driver.T4CTTIfun.receive(T4CTTIfun.java:522)
	at oracle.jdbc.driver.T4CTTIfun.doRPC(T4CTTIfun.java:257)
	at oracle.jdbc.driver.T4CTTIoauthenticate.doOAUTH(T4CTTIoauthenticate.java:437)
	at oracle.jdbc.driver.T4CTTIoauthenticate.doOAUTH(T4CTTIoauthenticate.java:954)
	at oracle.jdbc.driver.T4CConnection.logon(T4CConnection.java:639)
	at oracle.jdbc.driver.PhysicalConnection.connect(PhysicalConnection.java:666)
	at oracle.jdbc.driver.T4CDriverExtension.getConnection(T4CDriverExtension.java:32)
	at oracle.jdbc.driver.OracleDriver.connect(OracleDriver.java:566)
	at java_sql_DriverManager$getConnection.call(Unknown Source)
	at Conn_DB.connectDB(Conn_DB.groovy:63)
	at Conn_DB$connectDB.call(Unknown Source)
	at CustomKeywords.Conn_DB.connectDB(CustomKeywords.groovy:180)
	at try_it_out_Conn_DB.Conn_DB(try_it_out_Conn_DB.groovy:61)
	at ✽.Connect to Database(/Users/chaidir.pratama01/Katalon Studio/IST_Automation_Git/Include/features/IST_Real/SLIK/SLIK Gateway Customer/SELECT_KTP_NUMBER_CUSTOMER_from_DB.feature:25)
]]></failure>
</testcase>
</testsuite>
